version: '3.0'
services:
  database:
    image: mysql:8.0.29
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: portfolio_and_blog
      MYSQL_USER: vinimendes
      MYSQL_PASSWORD: D1squ3t3
